services:
  - type: web
    name: Athlete-Sync
    runtime: php
    buildCommand: composer install
    startCommand: apache2-foreground
    envVars:
      - key: PHP_EXTENSIONS
        value: pdo_pgsql
      - key: GEMINI_API_KEY
        sync: false
